name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app
      
      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test (macOS)
        run: |
          xcodebuild clean build test \
            -project CleanArchitecture.xcodeproj \
            -scheme CI_macOS \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -sdk macosx \
            -destination "platform=macOS" \
            ONLY_ACTIVE_ARCH=YES

      - name: Build and Test (iOS)
        run: |
          xcodebuild clean build test \
            -workspace CleanArchitectureApp.xcworkspace \
            -scheme CI_iOS \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            ONLY_ACTIVE_ARCH=YES
